on:
  push:
    paths:
      - 'plugins/**'
      - 'docs/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: solar2d/directory-plugin-action@main
        with:
          pat: ${{ secrets.ISSUE_PAT }}
